import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useLocation,useNavigate,useParams} from 'react-router-dom';
import {AnimatePresence,motion,useScroll,useSpring} from 'framer-motion';
import {MapPin,Phone,Clock,ArrowUpRight,ChevronDown,Menu as MenuIcon,X,Utensils,Leaf,Flame,GlassWater,Car,ShoppingBag,Truck,Navigation,Star,LogIn,UserPlus,Mail,LockKeyhole,CheckCircle2,Send,Play,CalendarDays} from 'lucide-react';
import './index.css';
import './styles.css';
import {auth, googleProvider, firebaseReady} from './firebase';
import {signInWithPopup,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendEmailVerification,updateProfile,signOut} from 'firebase/auth';

const InstagramIcon = ({ size = 20, strokeWidth = 2 }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={strokeWidth}
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <rect x="3" y="3" width="18" height="18" rx="5" />
    <circle cx="12" cy="12" r="4" />
    <circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none" />
  </svg>
);

const mapsUrl='https://www.google.com/maps/place/GRATIS+Fine+Dine+Bar/@18.5647147,73.7869081,15z/data=!4m15!1m8!3m7!1s0x3bc2bf6ea9dad4c5:0x772d73223f591d4f!2sGRATIS+Fine+Dine+Bar!8m2!3d18.5647787!4d73.7869555!10e1!16s%2Fg%2F11q1c_d9x9!3m5!1s0x3bc2bf6ea9dad4c5:0x772d73223f591d4f!8m2!3d18.5647787!4d73.7869555!16s%2Fg%2F11q1c_d9x9?entry=ttu';
const insta='https://www.instagram.com/gratispune/';
const zomato='https://www.zomato.com/pune/gratis-fine-dine-restaurant-baner';
const swiggy='https://www.swiggy.com/restaurants/pune/baner/gratis-fine-dine-bar-1158808/dineout';
const phone='09028426005';

const food={Veg:{
'Soups':['Tomato Soup','Veg Manchow Soup','Veg Sweet Corn Soup','Veg Hot & Sour Soup'],
'Tandoori Starters':['Harabhara Kabab','Tandoori Aloo','Tandoori Gobi','Paneer Tikka','Paneer Hariyali Tikka','Paneer Banjara Tikka','Paneer Mhakamali Kabab','Tandoori Mushroom Tikka','Paneer Sheek Kabab','Paneer Pahadi Kabab','Paneer Angara Kabab','Paneer Malai Kabab','Paneer Kurkure Kabab','Kabuli Kabab','Corn Sheek Kabab','Paneer Kasturi Tikka','Paneer Lasuni Tikka','Paneer Malwani Tikka','Gobi Tikka','Alu Tikka','Mushroom Tikka','Mushroom-ka-Nazakat','Veg Platter','Tandoori Babay Corn','Paneer Peri Peri Tikka'],
'Chinese Starters':['Crispy Veg','Veg 65','Veg Manchurian Dry','Paneer Chilli Dry','Sesame Paneer','Veg Spring Roll','Veg Salt & Pepper','Veg Hotpan','Veg Schezwan Dry','Veg Crunchy','Paneer Hotpan','Paneer Satay','Paneer Tempura','Crispy Sesame Paneer','Kum Pao Paneer','Mangolian Paneer','Gobi Manchurian','Baby Corn Chilly','Baby Corn Crispy','Mushroom Chilly','Mushroom Schezwan','Crispy Potato Chilly'],
'Main Course':['Mix Veg','Veg Kadhai','Veg Tawa','Aloo Gobi','Subzi Miloni','Veg Bhuna','Shabanmi Kumbh','Veg Toofani','Veg Chilli Milli','Veg Jalfrezi','Veg Kandari Masala','Veg Makhwanwala','Veg Patiala','Veg Diwani Handi','GRATIS Special Veg.','Paneer Nizami Handi','Paneer Kadai','Paneer Pasanda','Paneer Tikka Masala','Paneer Butter Masala','Paneer Laziz','Paneer Lababdar','Paneer Tawa Masala'],
'Chinese Gravy':['Veg in Hot Garlic Sauce','Veg Manchurian Gravy','Paneer Chilli Gravy'],
'Dal':['Dal Fry','Dal Lasooni Palak','Dal Tadka','Dal Makhani'],
'Breads':['Roti','Butter Roti','Naan','Butter Naan','Laccha Paratha','Onion Kulcha','Aloo Paratha','Mix Veg Paratha','Gobi Paratha','Garlic Naan','Cheese Garlic Naan','Cheese Naan','Paratha','Butter Paratha','Stuff Paratha'],
'Rice & Biryani':['Steamed Rice','Jeera Rice','Curd Rice','Green Peas Pulav','Barista Pulao','Veg Pulao','Dal Khichdi','Dal Palak','Veg Dum Biryani','Egg Biryani'],
'Fried Rice & Noodles':['Veg Fried Rice','Veg Schezwan Fried Rice','Veg Triple Schezwan Fried Rice','Veg Singapore Fried Rice','Egg Fried Rice','Veg Noodles','Veg Pan Fried Noodles','Veg Chilli Garlic Noodles','Veg Schezwan Noodles','Veg Triple Schezwan Noodles','Veg Singapore Noodles','Veg Hong Kong Style Noodles','Egg Noodles'],
'Accompaniments':['Roasted Papad','Masala Papad','Curd','Mixed Raita','Pineapple Raita','Green Salad'],
'Desserts':['Triple Sandae','Double Sandae','Sizzling Brownie','Choice Ice-cream','Matka Kulfi','Gulab Jamun','Gulab Jamun With Ice-cream'],
'Platters':['GRATIS Veg. Combo Platter','Veg. Chinese Platter','Veg. Tandoor Platter']},
NonVeg:{
'Soups':['Chicken Sweet Corn Soup','Non-Veg Sweet Corn Soup','Non-Veg Manchow Soup','Non-Veg Hot & Sour Soup'],
'Tandoori Starters':['Tandoori Chicken','Chicken Tikka','Chicken Lasooni Kabab','Chicken Kalimiri Kabab','Chicken Sholey Kabab','Chooza Kabab','Irani Tangadi Kabab (4 pcs)','Murg Angara Kabab','Murg Achari Kabab','Murg Sholey Kabab','Murg Reshmi Kabab','Murg Malai Kabab','Murg Kalimiri Kabab','Murg Banjara Kabab','Murg Rozali Kabab','Murg Kalmi Kabab'],
'Chinese Starters':['Chilli Chicken Dry','Chicken 65','Chicken in Hot Garlic Sauce','Crispy Chicken','Schezwan Chicken','Butter Garlic Chicken','Chicken Lollipop','Chicken Manchurian','Chicken Chilly','Chicken Hotpan','Chicken Chinese Satay'],
'Seafood':['Tandoori Fish Tikka','Fish Malwani Curry','Fish Goan Curry','Fish Manglorian Curry'],
'Main Course':['Chicken Tikka Masala','Chicken Handi','Chicken Sukka','Chicken Rara','Butter Chicken','Chicken Lababdar','Chicken Laziz','Chicken Kolhapuri','Chicken Nawabi Handi','Mutton Sukka','Mutton Tawa','Mutton Kadhai','Mutton Handi','Mutton Roganjosh','Mutton Rara','Murg Tikka Masala','Murg Kolhapuri','Murg Hyderabadi','Murg Adraki Masala','Murg Maratha','Murg Methiwala (B/L)','Murg Toofani (B/L)','Murg Bhuna (B/L)','Murg Tawa (B/L)','Murg Kadai (B/L)','Chicken Ra Ra Masala (Full)','Butter Chicken (Full)','Murg Mussalam (Full)','Murg Handi Kala Masala (Full)','Murg Navabi Handi (Full)','Murg Malwani (Full)','Murg Do Pyaza','Murg Patiala'],
'Gavaran':['Gavran Chicken Kala Masala','Gavran Chicken Sukha','Gavran Kala Masala','Gavran Malwani','Chicken Handi'],
'Mutton':['Mutton Handi Black Gravy (Full)','Mutton Navabi (Full)','Mutton Malwani (Full)','Mutton Rogan Josh','Mutton Maratha','Mutton Bhuna','Mutton Tawa','Mutton Kheema','Mutton Kadai','Mutton Rara'],
'Chinese Gravy':['Chilli Chicken Gravy','Chicken in Hunan Sauce','Chicken in Blackbean Sauce'],
'Rice & Biryani':['Chicken Dum Biryani','Mutton Dum Biryani'],
'Fried Rice & Noodles':['Chicken Fried Rice','Non-Veg Triple Schezwan Fried Rice','Non-Veg Schezwan Fried Rice','Non-Veg Singapore Fried Rice','Non-Veg Noodles','Non-Veg Pan Fried Noodles','Non-Veg Chilli Garlic Noodles','Non-Veg Schezwan Noodles','Non-Veg Triple Schezwan Noodles','Non-Veg Singapore Noodles','Non-Veg Hong Kong Style Noodles','Chicken Pan Fried Noodles','Chicken Singapore Noodles','Chicken American Chopsey'],
'Egg':['Egg Masala','Egg Curry','Egg Bhurji','Egg Omlet','Boiled Egg','Half Fry'],
'Platters':['GRATIS Sea Food Combo Platter','GRATIS Chicken Combo Platter','Chicken Chinese Platter','Chicken Tandoor Platter'],
'South Indian':['Chicken Neer Dosa','Neer Dosa (4 Nos)']}}

const priceMap={
'Tomato Soup':'₹140','Veg Manchow Soup':'₹140','Veg Sweet Corn Soup':'₹140','Veg Hot & Sour Soup':'₹140',
'Chicken Sweet Corn Soup':'₹170','Non-Veg Sweet Corn Soup':'₹170','Non-Veg Manchow Soup':'₹170','Non-Veg Hot & Sour Soup':'₹170',
'Harabhara Kabab':'₹240','Tandoori Aloo':'₹240','Tandoori Gobi':'₹240','Paneer Tikka':'₹260','Paneer Hariyali Tikka':'₹260','Paneer Banjara Tikka':'₹260','Tandoori Mushroom Tikka':'₹260',
'Veg. Sheek Kabab':'₹320','Paneer Sheek Kabab':'₹330','Paneer Pahadi Kabab':'₹330','Paneer Angara Kabab':'₹330','Paneer Malai Kabab':'₹330','Paneer Kurkure Kabab':'₹330','Paneer Banjara Kabab':'₹330','Kabuli Kabab':'₹330','Corn Sheek Kabab':'₹330','Paneer Kasturi Tikka':'₹320','Paneer Lasuni Tikka':'₹320','Paneer Malwani Tikka':'₹330','Gobi Tikka':'₹290','Alu Tikka':'₹270','Mushroom Tikka':'₹290','Mushroom-ka-Nazakat':'₹310','Veg Platter':'₹710','Tandoori Babay Corn':'₹320','Paneer Peri Peri Tikka':'₹330',
'Crispy Veg':'₹240','Veg 65':'₹240','Veg Manchurian Dry':'₹240','Paneer Chilli Dry':'₹260','Sesame Paneer':'₹260','Veg Spring Roll':'₹260','Veg Salt & Pepper':'₹260','Veg Hotpan':'₹290','Veg Schezwan Dry':'₹280','Veg Crunchy':'₹290','Paneer Hotpan':'₹290','Paneer Satay':'₹290','Paneer Tempura':'₹310','Crispy Sesame Paneer':'₹310','Kum Pao Paneer':'₹290','Mangolian Paneer':'₹290','Gobi Manchurian':'₹260','Baby Corn Chilly':'₹310','Baby Corn Crispy':'₹310','Mushroom Chilly':'₹310','Mushroom Schezwan':'₹310','Crispy Potato Chilly':'₹260',
'Chilli Chicken Dry':'₹290','Chicken 65':'₹290','Crispy Chicken':'₹290','Schezwan Chicken':'₹310','Butter Garlic Chicken':'₹310','Chicken in Hot Garlic Sauce':'₹310','Chicken Lollipop':'₹320','Chicken Manchurian':'₹320','Chicken Chilly':'₹320','Chicken Schezwan':'₹330','Chicken Hotpan':'₹330','Chicken Chinese Satay':'₹330',
'Tandoori Chicken':'₹270 / ₹410','Chicken Tikka':'₹340','Chicken Lasooni Kabab':'₹340','Chicken Kalimiri Kabab':'₹340','Chicken Sholey Kabab':'₹340','Chooza Kabab':'₹340','Irani Tangadi Kabab (4 pcs)':'₹350','Murg Tandoor (Full)':'₹550','Murg Tandoor (Half)':'₹320','Murg Angara Kabab':'₹400','Murg Achari Kabab':'₹400','Murg Sholey Kabab':'₹420','Murg Reshmi Kabab':'₹420','Murg Malai Kabab':'₹420','Murg Kalimiri Kabab':'₹400','Murg Banjara Kabab':'₹400','Murg Rozali Kabab':'₹420','Murg Kalmi Kabab':'₹400',
'Tandoori Fish Tikka':'₹APC','Fish Malwani Curry':'₹APC','Fish Goan Curry':'₹APC','Fish Manglorian Curry':'₹APC',
'Mix Veg':'₹240','Veg Kadhai':'₹240','Veg Tawa':'₹240','Aloo Gobi':'₹240','Subzi Miloni':'₹260','Veg Bhuna':'₹260','Shabanmi Kumbh':'₹260','Veg Toofani':'₹280','Veg Chilli Milli':'₹260','Veg Jalfrezi':'₹260','Veg Kandari Masala':'₹260','Veg Makhwanwala':'₹260','Veg Patiala':'₹300','Veg Diwani Handi':'₹300','GRATIS Special Veg.':'₹390','Paneer Nizami Handi':'₹320','Paneer Kadai':'₹300','Paneer Pasanda':'₹300','Paneer Tikka Masala':'₹300','Paneer Butter Masala':'₹280','Paneer Laziz':'₹280','Paneer Lababdar':'₹280','Paneer Tawa Masala':'₹280',
'Veg in Hot Garlic Sauce':'₹240','Veg Manchurian Gravy':'₹260','Paneer Chilli Gravy':'₹280','Chilli Chicken Gravy':'₹320','Chicken in Hunan Sauce':'₹320','Chicken in Blackbean Sauce':'₹320','Chicken in Hot Garlic Sauce':'₹320',
'Dal Fry':'₹220','Dal Lasooni Palak':'₹180','Dal Tadka':'₹240','Dal Makhani':'₹220','Dal Palak':'₹250',
'Roti':'₹40','Butter Roti':'₹50','Naan':'₹70','Butter Naan':'₹80','Garlic Naan':'₹110','Cheese Naan':'₹130','Cheese Garlic Naan':'₹140','Laccha Paratha':'₹110','Onion Kulcha':'₹130','Aloo Paratha':'₹70','Mix Veg Paratha':'₹70','Gobi Paratha':'₹70','Paratha':'₹80','Butter Paratha':'₹90','Stuff Paratha':'₹140',
'Steamed Rice':'₹100 / ₹150','Jeera Rice':'₹150 / ₹180','Curd Rice':'₹200','Green Peas Pulav':'₹210','Barista Pulao':'₹220','Veg Pulao':'₹240','Dal Khichdi':'₹240','Dal Palak':'₹250','Veg Dum Biryani':'₹250','Egg Biryani':'₹250','Chicken Dum Biryani':'₹310','Mutton Dum Biryani':'₹410',
'Veg Fried Rice':'₹250','Veg Schezwan Fried Rice':'₹270','Veg Triple Schezwan Fried Rice':'₹280','Veg Singapore Fried Rice':'₹280','Veg Noodles':'₹250','Veg Pan Fried Noodles':'₹260','Veg Chilli Garlic Noodles':'₹260','Veg Schezwan Noodles':'₹270','Veg Triple Schezwan Noodles':'₹280','Veg Singapore Noodles':'₹280','Veg Hong Kong Style Noodles':'₹280','Egg Fried Rice':'₹280','Egg Noodles':'₹280',
'Chicken Fried Rice':'₹280','Chicken Schezwan Fried Rice':'₹330','Chicken Triple Schezwan Fried Rice':'₹390','Chicken Hong Kong Fried Rice':'₹320','Chicken Peking Fried Rice':'₹320','Burnt Garlic Chicken Fried Rice':'₹320','Mix Fried Rice':'₹420','Seafood Fried Rice':'₹440','Egg Schezwan Fried Rice':'₹300','Chicken Pan Fried Noodles':'₹320','Chicken Singapur Noodles':'₹300','Chicken American Chopsey':'₹290','Non-Veg Triple Schezwan Fried Rice':'₹310','Non-Veg Schezwan Fried Rice':'₹300','Non-Veg Singapore Fried Rice':'₹310','Non-Veg Noodles':'₹280','Non-Veg Pan Fried Noodles':'₹290','Non-Veg Chilli Garlic Noodles':'₹290','Non-Veg Schezwan Noodles':'₹300','Non-Veg Triple Schezwan Noodles':'₹310','Non-Veg Singapore Noodles':'₹310','Non-Veg Hong Kong Style Noodles':'₹310',
'Roasted Papad':'₹30 / ₹50','Fried Papad':'₹50','Masala Papad':'₹80','French Fries':'₹150','Mix Raita':'₹130','Pineapple Raita':'₹130','Green Salad':'₹140','Curd':'₹100',
'Chicken Tikka Masala':'₹360','Chicken Handi':'₹360','Chicken Sukka':'₹360','Chicken Rara':'₹370','Butter Chicken':'₹380','Chicken Lababdar':'₹380','Chicken Laziz':'₹380','Chicken Kolhapuri':'₹380','Chicken Nawabi Handi':'₹380 / ₹580','Mutton Sukka':'₹410','Mutton Tawa':'₹410','Mutton Kadhai':'₹425','Mutton Handi':'₹425','Mutton Roganjosh':'₹425','Mutton Rogan Josh':'₹425','Mutton Rara':'₹430','Murg Tikka Masala':'₹380','Murg Kolhapuri':'₹360','Murg Hyderabadi':'₹360','Murg Adraki Masala':'₹360','Murg Maratha':'₹360','Murg Methiwala (B/L)':'₹400','Murg Toofani (B/L)':'₹400','Murg Bhuna (B/L)':'₹400','Murg Tawa (B/L)':'₹400','Murg Kadai (B/L)':'₹400','Murg Do Pyaza':'₹390','Murg Patiala':'₹420','Murg Tikka Masala':'₹380',
'Chicken Ra Ra Masala (With Born and Chicken Kheema) (Full)':'₹960','Chicken Ra Ra Masala (With Born and Chicken Kheema) (Half)':'₹510','Butter Chicken (Full)':'₹800','Butter Chicken (Half)':'₹440','Murg Mussalam (Full)':'₹980','Murg Mussalam (Half)':'₹540','Murg Handi Kala Masala (Full)':'₹800','Murg Handi Kala Masala (Half)':'₹440','Murg Navabi Handi (Full)':'₹850','Murg Navabi Handi (Half)':'₹450','Murg Malwani (Full)':'₹840','Murg Malwani (Half)':'₹460',
'Gavran Chicken Kala Masala':'₹880 / ₹450','Gavran Chicken Sukha':'₹880 / ₹450','Gavran Kala Masala':'₹950 / ₹520','Gavran Malwani':'₹950 / ₹520','Chicken Handi':'₹360','Mutton Handi Black Gravy (Full)':'₹870','Mutton Handi Black Gravy (Half)':'₹510','Mutton Navabi (Full)':'₹890','Mutton Navabi (Half)':'₹500','Mutton Malwani (Full)':'₹940','Mutton Malwani (Half)':'₹580','Mutton Rogan Josh':'₹470','Mutton Maratha':'₹470','Mutton Bhuna':'₹450','Mutton Tawa':'₹450','Mutton Kheema':'₹520','Mutton Kadai':'₹450','Mutton Rara':'₹470',
'Tomato Soup':'₹140','Triple Sandae':'₹340','Double Sundae':'₹240','Double Sandae':'₹240','Sizzling Brownie':'₹270','Choice Ice-cream':'₹170','Matka Kulfi':'₹120','Gulab Jamun':'₹120','Gulab Jamun With Ice-cream':'₹170','GRATIS Veg. Combo Platter':'₹1450','Veg. Chinese Platter':'₹750','Veg. Tandoor Platter':'₹820','GRATIS Sea Food Combo Platter':'₹APC','GRATIS Chicken Combo Platter':'₹1850','Chicken Chinese Platter':'₹1100','Chicken Tandoor Platter':'₹1200','Egg Masala':'₹260','Egg Curry':'₹230','Egg Bhurji':'₹170','Egg Omlet':'₹150','Boiled Egg':'₹100','Half Fry':'₹140','Chicken Neer Dosa':'₹310','Neer Dosa (4 Nos)':'₹130'
};

const bev=[
  ['Cocktails','Hand-shaken cocktails for slow evenings and rooftop breezes.'],
  ['Mocktails','Fresh, easygoing pours for every table.'],
  ['Draught & Bottled Beer','Cold pours for game nights and long dinners.'],
  ['Wines','Red, white and rosé selections.'],
  ['Spirits','Whisky, rum, vodka, gin and tequila.'],
  ['Soft Drinks & Fresh Juices','Bright, refreshing and simple.'],
  ['Tea / Coffee','A warm finish or a relaxed catch-up.']
];

const localImg=(name)=>`/assets/photos/${name}`;
const dishes=[
  ['Paneer Tikka',localImg('popular-06.jpg'),'Charred, herb-forward and made for sharing.','₹260'],
  ['Chicken Tikka',localImg('popular-01.jpg'),'Smoky tandoor edges with a generous, tender centre.','₹340'],
  ['Tandoori Fish Tikka',localImg('popular-09.jpg'),'A crisp, spiced fish plate with fresh chutney.','APC'],
  ['Sizzling Brownie',localImg('normal-03.jpg'),'Warm dessert, cool finish — a crowd-pleasing close.','₹270']
];
const gallery=[
  localImg('normal-02.jpg'),localImg('normal-13.jpg'),localImg('normal-10.jpg'),localImg('normal-07.jpg'),
  localImg('normal-14.jpg'),localImg('normal-05.jpg'),localImg('popular-09.jpg'),localImg('normal-04.jpg')
];

const reviews=[
  ['A really good place to sit and enjoy a drink.','Sushil Kumar'],
  ['Budget-friendly, with multiple screens and 90s music nights — a good hangout.','Atul Khopade'],
  ['Calm ambience, decent food and a comfortable spot for a quiet catch-up.','Prashant Pathade'],
  ['Food quality and taste were excellent, with fast service and a beautiful ambience.','Sonali Mahajan'],
  ['Cocktails, mocktails and seafood were standout choices on a family visit.','Harshal Eswar'],
  ['Good for friends because the garden area gives you room to settle in.','Guest review']
];

const detailGroups=[
  ['Service options',['No-contact delivery','Delivery','Drive-through','Takeaway','Dine-in']],
  ['Highlights',['Great beer selection','Great dessert']],
  ['Popular for',['Dinner','Solo dining']],
  ['Offerings',['Alcohol','All you can eat','Beer','Cocktails','Late-night food','Quick bite','Small plates','Spirits','Vegetarian options','Wine','Cuisine']],
  ['Dining options',['Lunch','Dinner','Dessert','Table service']],
  ['Amenities',['Bar on site','Restroom']],
  ['Atmosphere',['Casual','Cozy','Trendy']],
  ['Crowd',['Groups']],
  ['Payments',['Credit cards','Debit cards','NFC mobile payments']],
  ['Parking',['Free parking lot','Free street parking','Somewhat difficult to find a space']]
];

const signatureCopy={
  'Paneer Tikka':'Charred paneer, herbs and a smoky tandoor finish.',
  'Chicken Tikka':'Tender chicken with smoky edges and warming spices.',
  'Chicken Biryani':'Fragrant rice layered with slow-cooked chicken and spice.',
  'Tandoori Fish Tikka':'Spiced fish from the tandoor, served with fresh chutney.',
  'Butter Chicken':'A rich, creamy tomato gravy with a gentle smoky finish.'
};

function Reveal({children,className='',delay=0}){
  return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-70px'}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>
}
function Button({children,href,onClick,variant='primary',className='',type='button'}){
  const cls=`btn ${variant==='secondary'?'btn-secondary':'btn-primary'} ${className}`;
  return href ? <a className={cls} href={href}>{children}<ArrowUpRight size={16}/></a> : <button type={type} className={cls} onClick={onClick}>{children}<ArrowUpRight size={16}/></button>
}
function Header({openAuth}){
  const [open,setOpen]=useState(false); const loc=useLocation();
  const links=[['Home','/'],['Menu','/menu'],['About Us','/about'],['Visit Us','/visit']];
  return <header className="nav-wrap"><nav className="nav">
    <a href="/" className="brand"><img src="/assets/logo-yellow.png" alt="Gratis Fine Dine Bar"/><span>GRATIS<small>FINE-DINE · BAR</small></span></a>
    <div className={`navlinks ${open?'show':''}`}>
      {links.map(([n,p])=><a key={p} className={loc.pathname===p?'active':''} href={p} onClick={()=>setOpen(false)}>{n}</a>)}
      <button className="nav-auth" onClick={()=>{openAuth();setOpen(false)}}><LogIn size={15}/> Sign in</button>
    </div>
    <button className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button>
  </nav></header>
}
function MobileBar(){return <div className="mobile-bar"><a href={`tel:${phone}`}><Phone size={17}/>Call Now</a><a href={`tel:${phone}`}><CalendarDays size={17}/>Reserve</a></div>}
function Footer(){return <footer className="footer"><div className="footer-brand"><img src="/assets/logo-yellow.png" alt="Gratis Fine Dine Bar"/><p>Prathamesh Park, Baner, Pune 411069<br/>Beside Jupiter Hospital</p></div><div><p className="eyebrow">CONTACT</p><a href={`tel:${phone}`}>090284 26005</a><p>Opens 11:00 AM · closes late</p></div><div><p className="eyebrow">EXPLORE</p><a href="/menu">Menu</a><a href="/about">About Us</a><a href="/visit">Visit Us</a><a href={insta}>Instagram</a></div><div><p className="eyebrow">ORDER & MAP</p><a href={zomato}>Zomato</a><a href={swiggy}>Swiggy Dineout</a><a href={mapsUrl}>Google Maps</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Gratis Fine Dine Bar</span><span>Casual · Cozy · Trendy</span></div></footer>}
function App(){const [authOpen,setAuthOpen]=useState(false);return <><Header openAuth={()=>setAuthOpen(true)}/><AnimatePresence mode="wait"><RoutesContent openAuth={()=>setAuthOpen(true)}/></AnimatePresence><MobileBar/><Footer/><AuthModal open={authOpen} onClose={()=>setAuthOpen(false)}/></>}
function RoutesContent({openAuth}){const loc=useLocation();let C=Home;if(loc.pathname==='/menu')C=MenuPage;if(loc.pathname==='/about')C=AboutPage;if(loc.pathname==='/visit')C=VisitPage;return <motion.main key={loc.pathname} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.25}}><C openAuth={openAuth}/></motion.main>}
function Hero(){return <section className="hero"><div className="hero-media"><img src={localImg('normal-09.jpg')} alt="Gratis Fine Dine Bar exterior at night"/></div><div className="hero-overlay"/><div className="hero-content"><Reveal><p className="eyebrow">BANER, PUNE · NORTH INDIAN · BAR & KITCHEN</p><h1>Kebabs, cocktails,<br/><em>no reason to rush.</em></h1><p className="hero-copy">A relaxed Baner address for tandoor smoke, generous plates, cold pours and rooftop evenings that can run a little longer.</p><div className="hero-actions"><Button href={`tel:${phone}`}>Reserve a Table</Button><Button href="/menu" variant="secondary">Explore Menu</Button></div><div className="hero-note"><Star fill="currentColor" size={15}/> <b>4.0</b> from 223 Google reviews <span>·</span> ₹400–1,200 / person</div></Reveal></div><div className="hero-side"><span>ROOFTOP</span><span>BAR & KITCHEN</span><small>BANER · PUNE</small></div></section>}
function Trust(){return <section className="trust"><div><span className="trust-big">4.0★</span><span>223 Google reviews</span></div><div><span className="trust-big">₹400–1,200</span><span>approx. per person</span></div><div><span className="trust-big">4 cuisines</span><span>North Indian · Chinese · Mughlai · Sichuan</span></div><div className="service-icons"><span><Utensils/> Dine-in</span><span><ShoppingBag/> Takeaway</span><span><Truck/> Delivery</span><span><Car/> Drive-through</span></div></section>}
function Why(){const cards=[['01','Rooftop & garden seating','A little breeze, a little greenery, and enough room to settle in.'],['02','A full bar, your pace','Beer, wine, cocktails, mocktails and spirits — from first pour to last call.'],['03','Kitchen favourites','Kebabs, biryani, seafood and Chinese plates that keep tables ordering one more.'],['04','Premium feel. Honest spend.','A casual-trendy room without the fine-dining attitude.']];return <section className="section why"><Reveal><p className="eyebrow">THE GRATIS DIFFERENCE</p><h2>Made for the table<br/><em>and the mood.</em></h2></Reveal><div className="why-grid">{cards.map((c,i)=><Reveal delay={i*.08} key={c[0]}><article className="why-card"><span>{c[0]}</span><h3>{c[1]}</h3><p>{c[2]}</p></article></Reveal>)}</div></section>}
function MenuTeaser(){return <section className="section menu-teaser"><div className="menu-teaser-head"><Reveal><div><p className="eyebrow">FROM THE KITCHEN</p><h2>Plates worth<br/><em>coming back for.</em></h2><p className="section-intro">Real dishes from the restaurant's menu, paired with photography from Gratis itself.</p></div></Reveal><Reveal><Button href="/menu" variant="secondary">See Full Menu</Button></Reveal></div><div className="dish-grid">{dishes.slice(0,3).map((d,i)=><Reveal delay={i*.1} key={d[0]}><a href="/menu" className="dish-card"><div className="dish-image"><img src={d[1]} alt={d[0]}/><span className="dish-price">{d[3]}</span></div><div className="dish-copy"><span>Signature pick</span><h3>{d[0]}</h3><p>{d[2]}</p></div></a></Reveal>)}</div></section>}
function Gallery(){return <section className="gallery-section"><div className="gallery-title"><Reveal><p className="eyebrow">THE ROOM · THE PLATES</p><h2>Come for dinner.<br/><em>Stay for the atmosphere.</em></h2></Reveal></div><div className="gallery-grid">{gallery.map((g,i)=><motion.div key={g} className={`gallery-item gi-${i}`} whileHover={{scale:1.025,rotate:i%2?1:-1}} transition={{type:'spring',stiffness:240,damping:18}}><img src={g} alt="Gratis Fine Dine Bar" loading="lazy"/></motion.div>)}</div></section>}
function Insta(){const imgs=[localImg('normal-04.jpg'),localImg('popular-06.jpg'),localImg('normal-07.jpg'),localImg('popular-09.jpg'),localImg('normal-02.jpg'),localImg('normal-05.jpg')];return <section className="section insta"><Reveal><div className="section-head"><div><p className="eyebrow">FOLLOW THE FEED</p><h2>Baner, through<br/><em>the Gratis lens.</em></h2></div><Button href={insta} variant="secondary"><InstagramIcon size={17}/> Follow @gratispune</Button></div></Reveal><div className="insta-grid">{imgs.map((x,i)=><a href={insta} key={x} aria-label="Open Gratis Instagram"><img src={x} alt="Gratis food and ambience" loading="lazy"/><span><InstagramIcon size={16}/></span></a>)}</div></section>}
function Voices(){const [i,setI]=useState(0);useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%reviews.length),5200);return()=>clearInterval(t)},[]);return <section className="voices"><div><p className="eyebrow">GUEST VOICES</p><h2>What people<br/><em>come back for.</em></h2><p className="voice-source">Selected and paraphrased from the customer review material supplied for the site.</p></div><div className="quote-box"><AnimatePresence mode="wait"><motion.div key={i} initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-24}} transition={{duration:.45}}><div className="quote-mark">“</div><blockquote>{reviews[i][0]}</blockquote><p>{reviews[i][1]}</p></motion.div></AnimatePresence><div className="dots">{reviews.map((_,x)=><button key={x} className={x===i?'on':''} onClick={()=>setI(x)} aria-label={`Review ${x+1}`}/>)}</div></div></section>}
function Reserve(){return <section className="reserve" id="reserve"><div><p className="eyebrow">YOUR TABLE IS WAITING</p><h2>Make tonight<br/><em>feel easy.</em></h2><p>Prathamesh Park, Baner · beside Jupiter Hospital</p></div><div className="reserve-actions"><Button href={`tel:${phone}`}>Call to Reserve</Button><Button href={mapsUrl} variant="secondary">Get Directions</Button></div></section>}
function Home(){return <><Hero/><Trust/><Why/><MenuTeaser/><Gallery/><Insta/><Voices/><Reserve/></>}
function MenuPage(){const [top,setTop]=useState('Food');const [type,setType]=useState('Veg');return <><section className="page-hero"><div><p className="eyebrow">MENU · BANER, PUNE</p><h1>North Indian soul.<br/><em>Chinese heat.</em></h1><p>Explore the kitchen by category, then switch between vegetarian and non-vegetarian plates. Prices are shown from the supplied restaurant menu; seafood marked APC follows the printed menu notation.</p><div className="hero-actions"><Button href={`tel:${phone}`}>Reserve a Table</Button><Button href={swiggy} variant="secondary">Order via Dineout</Button></div></div><div className="page-hero-image"><img src={localImg('popular-09.jpg')} alt="Tandoori fish dish"/></div></section><section className="menu-shell"><div className="top-tabs"><button className={top==='Food'?'active':''} onClick={()=>setTop('Food')}><Utensils/> Food</button><button className={top==='Beverages'?'active':''} onClick={()=>setTop('Beverages')}><GlassWater/> Beverages</button></div><AnimatePresence mode="wait">{top==='Food'?<motion.div key="food" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><div className="segmented"><button className={type==='Veg'?'active':''} onClick={()=>setType('Veg')}><Leaf/> Veg</button><button className={type==='NonVeg'?'active':''} onClick={()=>setType('NonVeg')}><Flame/> Non-Veg</button></div><div className="menu-cats">{Object.entries(food[type]).map(([cat,items],i)=><Reveal key={cat} delay={Math.min(i*.025,.15)}><div className="menu-category"><div className="cat-head"><p>{String(i+1).padStart(2,'0')}</p><h2>{cat}</h2></div><div className="menu-list">{items.map(name=><div className="menu-row" key={name}><span className="dish-dot"/><span className="menu-name">{name}<small>{signatureCopy[name]||''}</small></span><strong className="menu-price">{priceMap[name]||'Ask server'}</strong></div>)}</div></div></Reveal>)}</div></motion.div>:<motion.div key="bev" className="beverages" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><p className="beverage-note">The full printed bar selection is not published online, so this page groups the available beverage types without inventing drink names or prices.</p><div className="bev-grid">{bev.map(([n,d],i)=><motion.article whileHover={{y:-6}} key={n}><span>0{i+1}</span><GlassWater size={22}/><h3>{n}</h3><p>{d}</p><small>Ask your server for today's selection</small></motion.article>)}</div></motion.div>}</AnimatePresence><div className="menu-cta"><div><p className="eyebrow">COME HUNGRY</p><h2>Let the table<br/><em>do the talking.</em></h2></div><div><Button href={`tel:${phone}`}>Reserve Your Table</Button><Button href={swiggy} variant="secondary">Order via Swiggy Dineout</Button></div></div></section></>}
function AboutPage(){return <><section className="page-hero about-hero"><div><p className="eyebrow">OUR STORY</p><h1>A neighborhood bar<br/><em>with a kitchen that means it.</em></h1><p>Gratis brings North Indian roots together with Chinese, Mughlai and Sichuan flavours in a casual-trendy bar and kitchen built for both quiet weekday drinks and lively dinners.</p><Button href="/visit">Come Say Hello</Button></div><div className="about-collage"><img src={localImg('normal-14.jpg')} alt="Gratis dining room"/><img src={localImg('popular-06.jpg')} alt="Gratis food"/><img src={localImg('normal-07.jpg')} alt="Gratis bar area"/></div></section><section className="story section"><Reveal><p className="eyebrow">A LOCAL RHYTHM</p><h2>Food first. <em>Always relaxed.</em></h2></Reveal><div className="story-grid"><Reveal><p>Known among Baner regulars for kebabs, biryani, seafood and Chinese plates, Gratis keeps the experience generous rather than formal. There is room for a quick bite, a long dinner, a rooftop drink or a table full of friends.</p></Reveal><Reveal delay={.1}><p>The full bar covers beer, wine, cocktails, mocktails and spirits. Rooftop and garden seating give the room an easy evening feel, while warm service and approachable pricing keep it grounded.</p></Reveal></div></section><section className="about-facts section"><Reveal><p className="eyebrow">THE DETAILS</p><h2>Everything you need<br/><em>before you arrive.</em></h2></Reveal><div className="facts-grid">{detailGroups.map(([title,items])=><article key={title}><span>{title}</span><ul>{items.map(x=><li key={x}><CheckCircle2 size={14}/>{x}</li>)}</ul></article>)}</div></section><section className="stats"><div><b>4.0★</b><span>rating</span></div><div><b>223+</b><span>reviews</span></div><div><b>₹400–1,200</b><span>per person</span></div><div><b>Baner</b><span>neighborhood favourite</span></div></section><section className="pillars section"><Reveal><p className="eyebrow">WHAT MATTERS HERE</p><h2>Three simple <em>promises.</em></h2></Reveal><div className="pillar-grid">{[['01','Honest Flavors','Big, familiar flavours without overcomplicating the plate.'],['02','Relaxed Hospitality','Quick, warm service that lets the table set the pace.'],['03','A Bar for Every Mood','From a quiet pour to a lively sports night.']].map((x,i)=><Reveal delay={i*.08} key={x[0]}><article><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article></Reveal>)}</div></section><Reserve/></>}
function VisitPage(){const faqs=[['Is parking available?','Yes. Free parking is available in the lot and on the street, although it can get busy.'],['Can I book for a large group?','For large groups and party orders, call the restaurant so the team can confirm the best arrangement.'],['Do you screen live sports?','Yes. The venue is known for live sports screenings, including IPL, plus occasional 90s music nights.'],['Are vegetarian options available?','Yes. The menu has a dedicated vegetarian selection across tandoori, Chinese, Indian mains, breads, rice and more.']];return <><section className="page-hero visit-hero"><div><p className="eyebrow">FIND US</p><h1>Baner's easiest<br/><em>table to get to.</em></h1><p>Prathamesh Park, beside Jupiter Hospital. Come for dinner, stay for the rooftop breeze.</p><div className="hero-actions"><Button href={mapsUrl}>Get Directions</Button><Button href={`tel:${phone}`} variant="secondary">Call to Reserve</Button></div><div className="visit-mini"><span><Clock size={15}/> Opens 11:00 AM</span><span><Car size={15}/> Free parking</span></div></div><div className="map-card"><iframe title="Gratis Fine Dine Bar map" src="https://www.google.com/maps?q=18.5647787,73.7869555&z=16&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></section><section className="visit-details section"><div className="contact-card"><MapPin/><div><p className="eyebrow">ADDRESS</p><h3>Prathamesh Park, Baner</h3><p>Pune, Maharashtra 411069<br/>Beside Jupiter Hospital</p></div></div><div className="contact-card"><Phone/><div><p className="eyebrow">PHONE</p><h3><a href={`tel:${phone}`}>090284 26005</a></h3><p>Tap to call the restaurant.</p></div></div><div className="contact-card"><Clock/><div><p className="eyebrow">HOURS</p><h3>Opens 11:00 AM daily</h3><p>Closes late night, around midnight.</p></div></div><div className="contact-card"><Car/><div><p className="eyebrow">PARKING</p><h3>Free lot + street parking</h3><p>Spaces can be somewhat difficult to find at peak times.</p></div></div></section><section className="services"><span><Utensils/> Dine-in</span><span><ShoppingBag/> Takeaway</span><span><Car/> Drive-through</span><span><Truck/> No-contact delivery</span><span><Truck/> Delivery</span></section><section className="section faq"><Reveal><p className="eyebrow">GOOD TO KNOW</p><h2>Before you <em>arrive.</em></h2></Reveal><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section><Insta/><Reserve/></>}
function AuthModal({open,onClose}){
  const [mode,setMode]=useState('signin'),[step,setStep]=useState('form'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!open){setStep('form');setStatus('');setCode('')}},[open]); if(!open)return null;
  const api=import.meta.env.VITE_AUTH_API_URL;
  const google=async()=>{if(!firebaseReady){setStatus('Firebase is not configured. Add your VITE_FIREBASE_* values to .env.');return}try{setBusy(true);await signInWithPopup(auth,googleProvider);setStatus('Signed in successfully.');setTimeout(onClose,700)}catch(e){setStatus(e.code?.replace('auth/','').replaceAll('-',' ')||e.message)}finally{setBusy(false)}};
  const sendCode=async()=>{if(!api){setStatus('Custom verification is not configured. Set VITE_AUTH_API_URL and start the auth server.');return}if(!email){setStatus('Enter your email first.');return}try{setBusy(true);const r=await fetch(`${api}/api/auth/send-code`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,name})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not send code');setStep('verify');setStatus('A 6-digit code was sent from Gratis Fine Dine Bar.')}catch(e){setStatus(e.message)}finally{setBusy(false)}};
  const verifyCode=async()=>{if(!api)return;try{setBusy(true);const r=await fetch(`${api}/api/auth/verify-code`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Verification failed');if(mode==='signup'&&firebaseReady){const c=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(c.user,{displayName:name});setStatus('Email verified and account created. Welcome to Gratis.');setTimeout(onClose,900)}else{setStatus('Email verified. You can continue.');setStep('form');setMode('signin')}}catch(e){setStatus(e.message)}finally{setBusy(false)}};
  const submit=async e=>{e.preventDefault();setStatus('');if(!firebaseReady){setStatus('Firebase is not configured. Add your credentials in .env.');return}try{setBusy(true);if(mode==='signin'){const c=await signInWithEmailAndPassword(auth,email,password);if(!c.user.emailVerified){await sendEmailVerification(c.user);setStatus('Firebase sent a verification email. Verify it, then sign in again.')}else if(api){setBusy(false);await sendCode()}else{setStatus('Welcome back.');setTimeout(onClose,700)}}else{if(api){setBusy(false);await sendCode()}else{const c=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(c.user,{displayName:name});await sendEmailVerification(c.user);setStatus('Account created. Check your email to verify it.')}}}catch(e){setStatus(e.code?.replace('auth/','').replaceAll('-',' ')||e.message)}finally{setBusy(false)}};
  return <div className="modal-backdrop" onMouseDown={onClose}><motion.div className="auth-card" onMouseDown={e=>e.stopPropagation()} initial={{opacity:0,y:24,scale:.97}} animate={{opacity:1,y:0,scale:1}} transition={{duration:.25}}><button className="modal-close" onClick={onClose} aria-label="Close sign in"><X/></button><div className="auth-brand"><img src="/assets/logo-yellow.png" alt="Gratis"/><div>GRATIS<small>FINE-DINE · BAR</small></div></div>{step==='verify'?<><p className="eyebrow">VERIFY YOUR EMAIL</p><h2>One last step.</h2><p className="auth-muted">Enter the 6-digit code sent to <b>{email}</b>.</p><input autoFocus value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} className="code-input" placeholder="000000" inputMode="numeric" maxLength={6}/><Button onClick={verifyCode}>{busy?'Checking…':'Verify email'}</Button><button className="code-link" onClick={sendCode} disabled={busy}><Send size={15}/> Resend code</button></>:<><div className="auth-switch"><button className={mode==='signin'?'active':''} onClick={()=>{setMode('signin');setStatus('')}}>Sign in</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setStatus('')}}>Create account</button></div><button className="google-btn" onClick={google} disabled={busy}><span>G</span> Continue with Google</button><div className="or"><span>or continue with email</span></div><form onSubmit={submit}>{mode==='signup'&&<label><span>Name</span><div className="field"><UserPlus/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/></div></label>}<label><span>Email</span><div className="field"><Mail/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div></label><label><span>Password</span><div className="field"><LockKeyhole/><input type="password" required minLength="6" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></div></label><Button className="auth-submit" type="submit">{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</Button></form>{mode==='signup'&&<button className="code-link" onClick={sendCode} disabled={busy}><Send size={15}/> Send a 6-digit verification code</button>}</>}{status&&<p className="auth-status"><CheckCircle2 size={16}/>{status}</p>}<p className="privacy-note">Your account is used only for the website's sign-in experience. Verification codes expire after 10 minutes.</p></motion.div></div>
}
function AppWithScroll(){const {scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:30,restDelta:.001});return <><motion.div className="progress" style={{scaleX}}/><App/></>}
createRoot(document.getElementById('root')).render(<BrowserRouter><AppWithScroll/></BrowserRouter>);
